
task_to_abbr = {'anaphor_gender_agreement': 'aga',
'anaphor_number_agreement' : 'ana',
'animate_subject_passive': 'asp',
'determiner_noun_agreement_1': 'dna',
'determiner_noun_agreement_irregular_1': 'dnai',
'determiner_noun_agreement_with_adjective_1': 'dnaa',
'determiner_noun_agreement_with_adj_irregular_1': 'dnaai',
'npi_present_1': 'npi',
'distractor_agreement_relational_noun' : 'darn',
'irregular_plural_subject_verb_agreement_1': 'ipsv',
'regular_plural_subject_verb_agreement_1': 'rpsv',
'sva_1': 'SVA 1',
'sva_2': 'SVA 2',
'sva_3': 'SVA 3',
'sva_4': 'SVA 4',
'ioi': 'IOI'}

dataset_2_ling_name = {
    'anaphor_gender_agreement': 'Anaphor Agreement',
    'anaphor_number_agreement': 'Anaphor Agreement',
    'animate_subject_passive' : 'Argument Structure',
    'determiner_noun_agreement_1': 'Determiner-Noun Agreement',
    'determiner_noun_agreement_irregular_1': 'Determiner-Noun Agreement',
    'determiner_noun_agreement_with_adjective_1': 'Determiner-Noun Agreement',
    'determiner_noun_agreement_with_adj_irregular_1': 'Determiner-Noun Agreement',
    'distractor_agreement_relational_noun': 'Subject-Verb Agreement',
     'npi_present_1': 'NPI Licensing',
    'ioi': 'Indirect Object Identification',
    'sva': 'Subject-Verb Agreement',
    'sva_1': 'Subject-Verb Agreement 1 Distractors',
    'sva_2': 'Subject-Verb Agreement 2 Distractors',
    'sva_3': 'Subject-Verb Agreement 3 Distractors',
    'sva_4': 'Subject-Verb Agreement 4 Distractors',

 }
